// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * SEO title field in *Home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.seo_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    seo_title: prismicT.RichTextField;
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = SkillsSlice | PresentationBannerSlice | SimpleContentSlice;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
export type AllDocumentTypes = HomeDocument;
/**
 * Primary content in PresentationBanner → Primary
 *
 */
interface PresentationBannerSliceDefaultPrimary {
    /**
     * Title field in *PresentationBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: presentation_banner.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *PresentationBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: presentation_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.TitleField;
    /**
     * Contact_Me field in *PresentationBanner → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: presentation_banner.primary.contact_me
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contact_me: prismicT.LinkField;
    /**
     * photo field in *PresentationBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: presentation_banner.primary.photo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    photo: prismicT.ImageField<never>;
}
/**
 * Default variation for PresentationBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PresentationBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PresentationBannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PresentationBannerSliceDefaultPrimary>, never>;
/**
 * Slice variation for *PresentationBanner*
 *
 */
type PresentationBannerSliceVariation = PresentationBannerSliceDefault;
/**
 * PresentationBanner Shared Slice
 *
 * - **API ID**: `presentation_banner`
 * - **Description**: `PresentationBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PresentationBannerSlice = prismicT.SharedSlice<"presentation_banner", PresentationBannerSliceVariation>;
/**
 * Primary content in SimpleContent → Primary
 *
 */
interface SimpleContentSliceDefaultPrimary {
    /**
     * Title field in *SimpleContent → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: simple_content.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *SimpleContent → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: simple_content.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for SimpleContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SimpleContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SimpleContentSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SimpleContentSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SimpleContent*
 *
 */
type SimpleContentSliceVariation = SimpleContentSliceDefault;
/**
 * SimpleContent Shared Slice
 *
 * - **API ID**: `simple_content`
 * - **Description**: `SimpleContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SimpleContentSlice = prismicT.SharedSlice<"simple_content", SimpleContentSliceVariation>;
/**
 * Item in Skills → Items
 *
 */
export interface SkillsSliceDefaultItem {
    /**
     * image field in *Skills → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Title field in *Skills → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *Skills → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Skills`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SkillsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SkillsSliceDefaultItem>>;
/**
 * Slice variation for *Skills*
 *
 */
type SkillsSliceVariation = SkillsSliceDefault;
/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: `Skills`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SkillsSlice = prismicT.SharedSlice<"skills", SkillsSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, AllDocumentTypes, PresentationBannerSliceDefaultPrimary, PresentationBannerSliceDefault, PresentationBannerSliceVariation, PresentationBannerSlice, SimpleContentSliceDefaultPrimary, SimpleContentSliceDefault, SimpleContentSliceVariation, SimpleContentSlice, SkillsSliceDefaultItem, SkillsSliceDefault, SkillsSliceVariation, SkillsSlice };
    }
}
