// Code generated by Slice Machine. DO NOT EDIT.

import Portfolio from './Portfolio';
import PresentationBanner from './PresentationBanner';
import SimpleContent from './SimpleContent';
import Skills from './Skills';
import TwoColumnTitleTex from './TwoColumnTitleTex';

export {
	Portfolio,
	PresentationBanner,
	SimpleContent,
	Skills,
	TwoColumnTitleTex,
};

export const components = {
	portfolio: Portfolio,
	presentation_banner: PresentationBanner,
	simple_content: SimpleContent,
	skills: Skills,
	two_column_title_tex: TwoColumnTitleTex,
};
