// Code generated by Slice Machine. DO NOT EDIT.

import PresentationBanner from './PresentationBanner';
import SimpleContent from './SimpleContent';
import Skills from './Skills';

export {
	PresentationBanner,
	SimpleContent,
	Skills,
};

export const components = {
	presentation_banner: PresentationBanner,
	simple_content: SimpleContent,
	skills: Skills,
};
